export const navigationItems = [
  { href: "/dashboard", label: "Dashboard" },
  { href: "/workflow", label: "Workflow" },
  { href: "/map-request", label: "Map Request" },
  { href: "/parcel-workspace", label: "Parcel Workspace" },
  { href: "/proximity", label: "Proximity" },
  { href: "/clarify", label: "Clarify Request" },
  { href: "/recipe-review", label: "Recipe Review" },
  { href: "/map-preview", label: "Map Preview" },
  { href: "/scenarios", label: "Scenarios" },
  { href: "/scenario-workbench", label: "Scenario Workbench" },
  { href: "/analysis", label: "Analysis" },
  { href: "/analysis-reports", label: "Analysis Reports" },
  { href: "/adjustments", label: "Adjustments" },
  { href: "/approval", label: "Approval" },
  { href: "/publish-center", label: "Publish Center" },
  { href: "/learning", label: "Learning" },
  { href: "/reports", label: "Reports" },
  { href: "/layer-catalog", label: "Layer Catalog" },
  { href: "/data-gaps", label: "Data Gaps" },
  { href: "/external-sources", label: "External Sources" },
  { href: "/history", label: "History" },
  { href: "/system-status", label: "System Status" },
];

export const samplePrompts = [
  "Show parcels in Concord that are in the 100-year floodplain.",
  "Show commercial zoning around Concord.",
  "Show school districts for parcels in Harrisburg.",
  "Show 2014 parcels and zoning.",
  "Map recent permits and planning cases near Kannapolis.",
  "Map commercial growth opportunities near high traffic roads but avoid floodplain.",
  "Make a map of parcel 5528-12-3456 and show zoning, floodplain, and nearby roads.",
  "How far is parcel 5528-12-3456 from the nearest school?",
];

export const workflowSteps = [
  { href: "/workflow", label: "Workflow", description: "Prompt to preview, adjust, analyze, and export." },
  { href: "/map-request", label: "Map Request", description: "Prompt to draft recipe." },
  { href: "/parcel-workspace", label: "Parcel Workspace", description: "Parcel IDs, PINs, addresses, and context maps." },
  { href: "/proximity", label: "Proximity", description: "Nearest facilities and straight-line route drafts." },
  { href: "/clarify", label: "Clarify Request", description: "Answer GIS review questions." },
  { href: "/recipe-review", label: "Recipe Review", description: "Layers, filters, gaps, and operations." },
  { href: "/map-preview", label: "Map Preview", description: "Local WebMap JSON preview." },
  { href: "/scenarios", label: "Scenarios", description: "Reviewable suitability frameworks." },
  { href: "/scenario-workbench", label: "Scenario Workbench", description: "Tune weights and compare variants." },
  { href: "/analysis", label: "Analysis", description: "Safe bounded local GeoJSON execution." },
  { href: "/adjustments", label: "Adjustments", description: "Human YAML adjustment loop." },
  { href: "/approval", label: "Approval", description: "Local readiness gate." },
  { href: "/publish-center", label: "Dry-Run Publish", description: "Dry-run receipts only." },
  { href: "/learning", label: "Learning", description: "Approved patterns and defaults." },
];
